project:
  type: website
  pre-render: node render-people.js

website:
  title: "DP-Next"
  site-url: "https://dp-next.github.io/"
  repo-url: "https://github.com/dp-next/dp-next.github.io"
  navbar:
    pinned: true
    left:
      - text: "Oversigt"
        href: index.qmd
      - text: "Deltager"
        href: 1homepage/deltager.qmd
      - text: "Forsker"
        href: 2overview/index.qmd
      - text: "Om Os"
        href: 4who_we_are/who-we-are.qmd
    right:
      - text: "Language"
        menu:
          - text: "ðŸ‡©ðŸ‡° Dansk"
            href: index.qmd
          - text: "ðŸ‡¬ðŸ‡§ English"
            href: en/index.qmd
    tools:
      - icon: github
        href: "https://github.com/dp-next/"

format:
  html:
    include-after-body: navbar-switcher.html

bibliography: references.bib
csl: vancouver.csl

editor: 
  markdown:
    wrap: 72
    canonical: true