project:
  render:
    - da/1homepage/index.qmd
    - da/2participant/deltager.qmd
    - da/3researcher/index.qmd
    - da/4wp/wp1/index.qmd
    - da/4wp/wp2/wp2.qmd
    - da/4wp/wp3/wp3.qmd
    - da/4wp/wp4/wp4.qmd
    - da/5whoweare/who-we-are.qmd
    - da/6publications/publications.qmd
    - da/7support/support.qmd

website:
  site-url: "https://dp-next.github.io/da/"
  navbar:
    left:
      - text: "Deltager"
        href: /da/2participant/deltager.html
      - text: "Forsker"
        href: /da/3researcher/index.html
      - text: "Work Packages"
        menu:
          - text: "WP1"
            href: /da/4wp/wp1/index.html
          - text: "WP2"
            href: /da/4wp/wp2/wp2.html
          - text: "WP3"
            href: /da/4wp/wp3/wp3.html
          - text: "WP4: Intervention Development"
            href: /da/4wp/wp4/wp4.html
      - text: "Om Os"
        href: /da/5whoweare/who-we-are.html
      - text: "Publications"
        href: /da/6publications/publications.html
      - text: "Support"
        href: /da/7support/support.html
