project:
  type: website
  pre-render: node render-people.js
  render:
    - en/1homepage/index.qmd
    - en/1homepage/deltager.qmd
    - en/2overview/index.qmd
    - en/3wp/wp1/index.qmd
    - en/3wp/wp2/wp2.qmd
    - en/3wp/wp3/wp3.qmd
    - en/3wp/wp4/wp4.qmd
    - en/4who_we_are/who-we-are.qmd
    - en/5publications/publications.qmd
    - en/6support/support.qmd

website:
  title: "DP-Next"
  site-url: "https://dp-next.github.io/en/"
  repo-url: "https://github.com/dp-next/dp-next.github.io"
  navbar:
    pinned: true
    left:
      - text: "Language"
        menu:
          - text: "Dansk"
            href: /da/1homepage/index.html
          - text: "English"
            href: /en/1homepage/index.html
      - text: "Participant"
        href: en/1homepage/deltager.qmd
      - text: "Researcher"
        href: en/2overview/index.qmd
      - text: "Work Packages"
        menu:
          - text: "WP1"
            href: en/3wp/wp1/index.qmd
          - text: "WP2"
            href: en/3wp/wp2/wp2.qmd
          - text: "WP3"
            href: en/3wp/wp3/wp3.qmd
          - text: "WP4: Intervention Development"
            href: en/3wp/wp4/wp4.qmd
      - text: "Who We Are"
        href: en/4who_we_are/who-we-are.qmd
      - text: "Publications"
        href: en/5publications/publications.qmd
      - text: "Support"
        href: en/6support/support.qmd
    tools:
      - icon: github
        href: "https://github.com/dp-next/"

format:
  html:
    include-after-body: language-switch.html

bibliography: references.bib
csl: vancouver.csl

editor:
  markdown:
    wrap: 72
    canonical: true