project:
  type: website

website:
  title: "DP-Next"
  site-url: "https://dp-next.github.io/"
  repo-url: "https://github.com/dp-next/dp-next.github.io"
  navbar:
    pinned: true
    left:
      - 1homepage/index.qmd
      - text: "Deltager"
        href: 1homepage/deltager/index.qmd
      - text: "Forsker"
        href: 1homepage/forsker/index.qmd
        - text: "WP4: Intervention Development"
          href: 3wp/wp4/wp4.qmd 
      - text: Who We Are
        href: 4who_we_are/who-we-are.qmd
    tools:
      - icon: github
        href: "https://github.com/dp-next/"

format: 
  html

bibliography: references.bib
csl: vancouver.csl

editor: 
  markdown:
    wrap: 72
    canonical: true
