project:
  type: website
  output-dir: _site
  pre-render: node _templates/render-people.js
  render:
    - en/1homepage/index.qmd
    - en/2participant/deltager.qmd
    - en/3researcher/index.qmd
    - en/4wp/wp1/index.qmd
    - en/4wp/wp2/wp2.qmd
    - en/4wp/wp3/wp3.qmd
    - en/4wp/wp4/wp4.qmd
    - en/5whoweare/who-we-are.qmd
    - en/6publications/publications.qmd
    - en/7support/support.qmd
  resources:
    - images/**
    - settings/**
    - language-switch.html
    - site_libs/**
    - data/**

website:
  title: "DP-Next"
  site-url: "https://dp-next.github.io/en/"
  repo-url: "https://github.com/dp-next/dp-next.github.io"
  navbar:
    pinned: true
    left:
      - text: "Language"
        menu:
          - text: "Dansk"
            href: /da/1homepage/index.html
          - text: "English"
            href: /en/1homepage/index.html
      - text: "Participant"
        href: /en/2participant/deltager.html
      - text: "Researcher"
        href: /en/3researcher/index.html
      - text: "Work Packages"
        menu:
          - text: "WP1"
            href: /en/4wp/wp1/index.html
          - text: "WP2"
            href: /en/4wp/wp2/wp2.html
          - text: "WP3"
            href: /en/4wp/wp3/wp3.html
          - text: "WP4: Intervention Development"
            href: /en/4wp/wp4/wp4.html
      - text: "Who We Are"
        href: /en/5whoweare/who-we-are.html
      - text: "Publications"
        href: /en/6publications/publications.html
      - text: "Support"
        href: /en/7support/support.html
    right:
      - text: "Language"
        menu:
          - text: "Dansk"
            href: /da/1homepage/index.html
          - text: "English"
            href: /en/1homepage/index.html
    tools:
      - icon: github
        href: "https://github.com/dp-next/"

format:
  html:
    include-after-body: language-switch.html
    css: /settings/style.css

bibliography: settings/references.bib
csl: settings/vancouver.csl

editor:
  markdown:
    wrap: 72
    canonical: true
