project:
  type: website
  output-dir: _site
  pre-render: node _templates/render-people.js
  resources:
    - images/**
    - settings/**
    - language-switch.html
    - data/**

website:
  title: "DP-Next"
  site-url: "https://dp-next.github.io/da/"
  repo-url: "https://github.com/dp-next/dp-next.github.io"
  navbar:
    pinned: true
    left:
      - text: "Language"
        menu:
          - text: "Dansk"
            href: /da/1homepage/index.qmd
          - text: "English"
            href: /en/1homepage/index.qmd
      - text: "Deltager"
        href: /da/2participant/deltager.qmd
      - text: "Participant"
        href: /en/2participant/deltager.qmd
      - text: "Forsker"
        href: /da/3researcher/index.qmd
      - text: "Researcher"
        href: /en/3researcher/index.qmd
      - text: "Work Packages"
        menu:
          - text: "WP1"
            href: /da/4wp/wp1/index.qmd
          - text: "WP1"
            href: /en/4wp/wp1/index.qmd
          - text: "WP2"
            href: /da/4wp/wp2/wp2.qmd
          - text: "WP2"
            href: /en/4wp/wp2/wp2.qmd
          - text: "WP3"
            href: /da/4wp/wp3/wp3.qmd
          - text: "WP3"
            href: /en/4wp/wp3/wp3.qmd
          - text: "WP4: Intervention Development"
            href: /da/4wp/wp4/wp4.qmd
          - text: "WP4: Intervention Development"
            href: /en/4wp/wp4/wp4.qmd
      - text: "Om Os"
        href: /da/5whoweare/who-we-are.qmd
      - text: "Who We Are"
        href: /en/5whoweare/who-we-are.qmd
      - text: "Publications"
        href: /da/6publications/publications.qmd
      - text: "Publications"
        href: /en/6publications/publications.qmd
      - text: "Support"
        href: /da/7support/support.qmd
      - text: "Support"
        href: /en/7support/support.qmd
    tools:
      - icon: github
        href: "https://github.com/dp-next/"

format:
  html:
    include-after-body: language-switch.html
    css: /settings/style.css

bibliography: settings/references.bib
csl: settings/vancouver.csl

editor:
  markdown:
    wrap: 72
    canonical: true