project:
  type: website

website:
  title: "DP-Next"
  site-url: "https://dp-next.github.io/"
  repo-url: "https://github.com/dp-next/dp-next.github.io"
  navbar:
    pinned: true
    left:
      - index.qmd
      - text: "Work packages"
        menu:
        - wp1/index.qmd
        - text: "WP2: Risk Prediction"
          href: wp2.qmd
        - text: "WP3: Heterogeneity"
          href: wp3.qmd
        - text: "WP4: Intervention Development"
          href: wp4.qmd
      - text: Who We Are
        href: who-we-are.qmd
      - text: Publications
        href: publications.qmd
      - text: Support
        href: support.qmd
    tools:
      - icon: github
        href: "https://github.com/dp-next/"

format:
  html

bibliography: references.bib
csl: vancouver.csl

editor:
  markdown:
    wrap: 72
    canonical: true
