project:
  type: website
  output-dir: ../_site
  resources:
    - ../images/**
    - ../settings/**
    - ../site_libs/**
    - ../data/**

website:
  title: "DP-Next"
  repo-url: "https://github.com/dp-next/dp-next.github.io"
  navbar:
    pinned: true
    right:
      - text: "Language"
        menu:
          - text: "Dansk"
            href: /da/1homepage/index.html
          - text: "English"
            href: /en/1homepage/index.html
    tools:
      - icon: github
        href: "https://github.com/dp-next/"

format:
  html:
    css: /settings/style.css

bibliography: ../settings/references.bib
csl: ../settings/vancouver.csl

editor:
  markdown:
    wrap: 72
    canonical: true
